SportsFinder/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SportsFinder.Data;
using SportsFinder.Data.Models;
using SportsFinder.ViewModels;

namespace SportsFinder.Controllers
{
    public class EventsController : Controller
    {
        public ApplicationDbContext DB { get; }
        private readonly UserManager<ApplicationUser> userManager;
        public EventsController(ApplicationDbContext _db, UserManager<ApplicationUser> _userManager)
        {
            DB = _db;
            userManager = _userManager;
        }
        public IActionResult Index()
        {
            var Events = DB.Events
                .Include(x => x.Sport)
                .Include(x => x.Gender)
                .Include(x => x.SkillLevel)
                .Include(x => x.Players)
                .Include(x => x.Creator).Where(x => x.EventDate > DateTime.Now);
            return View(Events);
        }


        [Authorize]
        public IActionResult Create()
        {
            EventCreateViewModel evm = new EventCreateViewModel();
            evm.Sports = DB.Sports.ToList();
            evm.SkillLevels = DB.SkillLevels.ToList();
            evm.PreferredGenders = DB.PreferredGenders.ToList();
            return View(evm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Event evt)
        {
            var user = userManager.GetUserId(HttpContext.User);
            evt.CreatorId = user;
            evt.DateCreated = DateTime.Now;
            evt.EventStatusId = 1;
            if (!ModelState.IsValid)
            {
                //get key(s) and error message(s) from the ModelState
                var serializableModelState = new SerializableError(ModelState);

                //convert to a string
                var modelStateJson = JsonConvert.SerializeObject(serializableModelState);

                return BadRequest(modelStateJson);
            }



            DB.Events.Add(evt);
            DB.SaveChanges();


            Player P = new Player();
            P.UserId = user;
            P.EventId = evt.EventId;
            P.UserStatusId = 1;
            DB.Players.Add(P);
            DB.SaveChanges();

            return RedirectToAction("Details", new { id = evt.EventId });
        }
        public IActionResult Details(int id)
        {
            var ev = DB.Events.Where(y => y.EventId == id)
                .Include(x => x.Players).ThenInclude(c => c.User).ThenInclude(y => y.Gender)
                .Include(x => x.Sport)
                .Include(x => x.Gender)
                .Include(x => x.SkillLevel)
                .Include(x => x.Creator).Single();

            return View(ev);
        }
        [HttpPost]
        public IActionResult Join(int id)
        {
            var user = userManager.GetUserId(HttpContext.User);
            Event currEvent = DB.Events.Where(ev => ev.EventId == id).Include(ev => ev.Players).FirstOrDefault();

            if (currEvent == null)
            {
                return NotFound();
            }
            if (!currEvent.Players.Any(p => p.UserId == user))
            {
                Player P = new Player();
                P.UserId = user;
                P.EventId = currEvent.EventId;
                P.UserStatusId = 1;
                DB.Players.Add(P);
                DB.SaveChanges();
            }
            else
            {
                Player removePlayer = DB.Players.Where(p => p.UserId == user && p.EventId == currEvent.EventId).FirstOrDefault();
                DB.Players.Remove(removePlayer);
                DB.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult JoinDetails(int id)
        {
            var user = userManager.GetUserId(HttpContext.User);
            Event currEvent = DB.Events.Where(ev => ev.EventId == id).Include(ev => ev.Players).FirstOrDefault();

            if (currEvent == null)
            {
                return NotFound();
            }
            if (!currEvent.Players.Any(p => p.UserId == user))
            {
                Player P = new Player();
                P.UserId = user;
                P.EventId = currEvent.EventId;
                P.UserStatusId = 1;
                DB.Players.Add(P);
                DB.SaveChanges();
            }
            else
            {
                Player removePlayer = DB.Players.Where(p => p.UserId == user && p.EventId == currEvent.EventId).FirstOrDefault();
                DB.Players.Remove(removePlayer);
                DB.SaveChanges();
            }

            return RedirectToAction("Details", new { id = id });
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            EventEditViewModel evm = new EventEditViewModel();
            var evt = DB.Events.Where(ev => ev.EventId == id)
                .Include(x => x.Players).ThenInclude(c => c.User).ThenInclude(y => y.Gender)
                .Include(x => x.Sport)
                .Include(x => x.Gender)
                .Include(x => x.SkillLevel)
                .Include(x => x.Creator);
            evm.Sports = DB.Sports.ToList();
            evm.SkillLevels = DB.SkillLevels.ToList();
            evm.PreferredGenders = DB.PreferredGenders.ToList();
            evm.Event = evt.FirstOrDefault();
            return View(evm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Edit(Event evt)
        {
            var currentEvent = DB.Events.Where(x => x.EventId == evt.EventId).FirstOrDefault();
            var user = userManager.GetUserId(HttpContext.User);

            if (!ModelState.IsValid)
            {
                //get key(s) and error message(s) from the ModelState
                var serializableModelState = new SerializableError(ModelState);

                //convert to a string
                var modelStateJson = JsonConvert.SerializeObject(serializableModelState);

                return BadRequest(modelStateJson);
            }

            currentEvent.EventDate = evt.EventDate;
            currentEvent.Title = evt.Title;
            currentEvent.Description = evt.Description;
            currentEvent.Location = evt.Location;
            currentEvent.SportId = evt.SportId;
            currentEvent.PlayersNeeded = evt.PlayersNeeded;
            currentEvent.GenderId = evt.GenderId;
            currentEvent.SkillLevelId = evt.SkillLevelId;


            DB.Events.Update(currentEvent);
            DB.SaveChanges();

            return RedirectToAction("Details", new { id = currentEvent.EventId });
        }
    }
}

SportsFinder/Controllers/ExamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SportsFinder.Data;
using SportsFinder.Data.Models;

namespace SportsFinder.Controllers
{
    public class ExamplesController : Controller
    {

        public ApplicationDbContext DB { get; }

        public ExamplesController(ApplicationDbContext _db)
        {
            DB = _db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Vue()
        {
            return View();
        }

        public IActionResult Get()
        {
            var data = WeatherForecasts();
            return View(data);
        }

        public IActionResult Post()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Post(WeatherForecast wf)
        {
            return View(wf);
        }

        public IActionResult VueGet()
        {
            return View();
        }

        public IActionResult VuePost()
        {
            return View();
        }


        //If you want to POST json data, you need to add [FromBody]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult VuePostJSON([FromBody] IEnumerable<WeatherForecast> wflist)
        {
            if (!ModelState.IsValid)
            {
                //get key(s) and error message(s) from the ModelState
                var serializableModelState = new SerializableError(ModelState);

                //convert to a string
                var modelStateJson = JsonConvert.SerializeObject(serializableModelState);

                return BadRequest(modelStateJson);
            }

            return Ok(wflist);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult VuePost(IEnumerable<WeatherForecast> wflist)
        {
            if (!ModelState.IsValid)
            {
                //get key(s) and error message(s) from the ModelState
                var serializableModelState = new SerializableError(ModelState);

                //convert to a string
                var modelStateJson = JsonConvert.SerializeObject(serializableModelState);

                return BadRequest(modelStateJson);
            }

            return Ok(wflist);
        }





        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };


        public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                DateFormatted = DateTime.Now.AddDays(index).ToString("d"),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
        }        
    }
}

SportsFinder/Controllers/GenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SportsFinder.Controllers
{
    public class GenderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SportsFinder/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportsFinder.Data;
using SportsFinder.Data.Models;

namespace SportsFinder.Controllers
{
    public class MessageController : Controller
    {
        public ApplicationDbContext DB { get; }
        private readonly UserManager<ApplicationUser> userManager;
        public MessageController(ApplicationDbContext _db, UserManager<ApplicationUser> _userManager)
        {
            DB = _db;
            userManager = _userManager;
        }
        [Authorize]
        public IActionResult Index()
        {
            var user = userManager.GetUserId(HttpContext.User);
            var Messages = DB.Messages.Where(x=> x.MessageTo.Id == user || x.MessageTo.Id ==user)
                .Include(x => x.MessageStatus);
                
            return View(Messages);
        }
        [Authorize]
        public IActionResult Send(int id)
        {
            //EventEditViewModel evm = new EventEditViewModel();
            //var evt = DB.Events.Where(ev => ev.EventId == id)
            //    .Include(x => x.Players).ThenInclude(c => c.User).ThenInclude(y => y.Gender)
            //    .Include(x => x.Sport)
            //    .Include(x => x.Gender)
            //    .Include(x => x.SkillLevel)
            //    .Include(x => x.Creator);
            //evm.Sports = DB.Sports.ToList();
            //evm.SkillLevels = DB.SkillLevels.ToList();
            //evm.PreferredGenders = DB.PreferredGenders.ToList();
            //evm.Event = evt.FirstOrDefault();
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Send(Message msg)
        {
            var user = userManager.GetUserId(HttpContext.User);
           
            msg.MessageFrom = DB.Users.Where(p => p.Id == user).FirstOrDefault();
            DB.Messages.Add(msg);
            DB.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

SportsFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html  lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="">
    <meta name="theme-color" content="#fafafa">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="turbolinks-cache-control" content="no-cache">

    <link rel="apple-touch-icon" href="~/icon.png">
    <link rel="manifest" href="~/site.webmanifest">


    @RenderSection("Head", required: false)

    <title>@ViewData["Title"] - SportsFinder</title>
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" id="main-css-link" href="~/css/app.min.css" asp-append-version="true" class="main-css-link-class" data-turbolinks-permanent />

    <script type="text/javascript">
        window.baseUrl = "@Url.Content("~/")";
    </script>

    <!-- Scripts are in the head to not be redownloaded because of Turbo Links -->
    <environment include="Development">
        <script src="~/js/dist/vendor.min.dev.js" asp-append-version="true"></script>
        <script src="~/js/app.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/dist/vendor.min.js" asp-append-version="true"></script>
        <script src="~/js/dist/app.min.js" asp-append-version="true"></script>
    </environment>

</head>
<body>
    <div id="app" class="app header-fixed sidebar-fixed">
        <header class="header">
            <div class="header-block header-block-collapse is-hidden-desktop">
                <button class="collapse-btn" id="sidebar-collapse-btn" onclick="openSidebar()">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="header-block header-block-nav is-hidden-desktop">
                <div class="brand">
                    <a class="has-text-dark is-size-4" asp-area="" asp-controller="Home" asp-action="Index">
                        <partial name="_Logo" />
                    </a>
                </div>
            </div>
            <div class="header-block header-block-nav">
                <partial name="_LoginPartial" />
            </div>
        </header>
        <aside class="sidebar has-background-dark">
            <div class="sidebar-header">
                <div class="brand ">

                    <a class="has-text-light is-size-4" asp-area="" asp-controller="Home" asp-action="Index">
                        <partial name="_Logo" />
                    </a>
                </div>
            </div>
            <nav class="menu">
                <ul class="menu-list" id="sidebar-menu">
                    <li>
                        <a class="has-text-light" asp-area="" asp-controller="Home" asp-action="Index" is-active-route><i class="fas fa-home"></i> Home</a>
                    </li>
                    <li>
                        <a class="has-text-light" asp-area="" asp-controller="Events" asp-action="Index" is-active-route><i class="fas fa-list-ul"></i> Events</a>
                    </li>
                    <li>
                        <a class="has-text-light" asp-area="" asp-controller="Message" asp-action="Index" is-active-route><i class="fas fa-envelope"></i> Messsages</a>
                    </li>
                    
                    @*<li>
            <a class="has-text-light" asp-area="" asp-controller="Home" asp-action="Index" is-active-route><i class="fas fa-bell"></i> Notifications</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Gender" asp-action="Index" is-active-route><i class="fas fa-user-cog"></i> Settings</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Home" asp-action="Privacy" is-active-route><i class="fas fa-user-shield"></i> Privacy</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Examples" asp-action="Get" is-active-route><i class="fas fa-basketball-ball"></i> Get Example</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Examples" asp-action="Post" is-active-route><i class="fas fa-upload"></i> Post Example</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Examples" asp-action="Vue" is-active-route><i class="fab fa-vuejs"></i> Vue Example</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Examples" asp-action="VueGet" is-active-route><i class="fab fa-vuejs"></i><i class="fas fa-download"></i> Vue Get Example</a>
        </li>
        <li>
            <a class="has-text-light" asp-area="" asp-controller="Examples" asp-action="VuePost" is-active-route><i class="fab fa-vuejs"></i><i class="fas fa-upload"></i> Vue Post Example</a>
        </li>*@


                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>
                            <a class="has-text-light" asp-area="" asp-controller="Admin" asp-action="Users" is-active-route><i class="fa fa-users"></i> Users</a>
                        </li>
                        <li>
                            <a class="has-text-light" asp-area="" asp-controller="Admin" asp-action="Events" is-active-route><i class="fa fa-calendar"></i> Past Events</a>
                        </li>
                    }
                </ul>
            </nav>
        </aside>
        <div class="sidebar-overlay" id="sidebar-overlay" data-turbolinks-permanent></div>
        <article class="content dashboard-page">
            <section role="main" class="container is-fluid">
                @RenderBody()
            </section>
        </article>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - SportsFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

SportsFinder/Views/Shared/_LayoutNoNavigation.cshtml
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="turbolinks-cache-control" content="no-cache">

    @RenderSection("Head", required: false)

    <title>@ViewData["Title"] - SportsFinder</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/app.css" />

    <!-- Scripts are in the head to not be redownloaded because of Turbo Links -->
    <environment include="Development">
        <script src="~/js/dist.min.dev.js"></script>
        <script src="~/js/app.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/dist.min.js"></script>
        <script src="~/js/app.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body class="loaded">
    <div id="app" class="auth">
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

SportsFinder/Views/Shared/_Logo.cshtml
SportsFinder